apiVersion: apps/v1
kind: Deployment
metadata:
  name: showreadiness
spec:
  revisionHistoryLimit: 5
  replicas: 3
  selector:
    matchLabels:
      app: showreadiness
  template:
    metadata:
      labels:
        app: showreadiness
    spec:
      containers:
      - name: showreadiness
        image: showreadiness:1 #Your Repo Here
        livenessProbe:
            httpGet:
                path: /ping
                port: 80
                scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 2
        readinessProbe:
            httpGet:
                path: /ready
                port: 80
                scheme: HTTP
            initialDelaySeconds: 12
            timeoutSeconds: 1              
        resources:
          requests:
            memory: 16Mi
          limits:
            memory: 16Mi
