apiVersion: v1
kind: Service
metadata:
  name: showreadiness
  labels:
    app: showreadiness
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: showreadiness
    port: 80 # Internal Port
    targetPort: 6080 # External port
    protocol: TCP 
  selector:
    app: showreadiness
